# generated by n64split
.section .rodata
.include "macros.inc"
.include "PR/gbi.inc"
.include "collision.inc"
.include "macro_presets.inc"
.include "special_presets.inc"

.include "levels/castle_courtyard/texture.s"
.include "levels/castle_courtyard/areas/1/1/model.s"
.include "levels/castle_courtyard/areas/1/spire/model.s"
.include "levels/castle_courtyard/areas/1/2/model.s"
.include "levels/castle_courtyard/areas/1/3/model.s"
.include "levels/castle_courtyard/areas/1/collision.s"
.include "levels/castle_courtyard/areas/1/macro.s"
.include "levels/castle_courtyard/areas/1/movtext.s"
