# Generated by LakiTool

glabel bbh_seg7_collision_07026B1C # 0x07026B1C - 0x07026B4C
colInit
colVertexInit 0x4
colVertex 102, 0, -50
colVertex -101, 0, -50
colVertex -101, 0, 51
colVertex 102, 0, 51
colTriInit SURF_NOISE_DEF, 2
colTri 0, 1, 2
colTri 0, 2, 3
colTriStop
colEnd
