# generated by n64split
.section .rodata
.include "macros.inc"
.include "PR/gbi.inc"
.include "collision.inc"
.include "macro_presets.inc"
.include "special_presets.inc"

.include "levels/castle_grounds/texture.s"
.include "levels/castle_grounds/areas/1/1/model.s"
.include "levels/castle_grounds/areas/1/2/model.s"
.include "levels/castle_grounds/areas/1/3/model.s"
.include "levels/castle_grounds/areas/1/4/model.s"
.include "levels/castle_grounds/areas/1/5/model.s"
.include "levels/castle_grounds/areas/1/6/model.s"
.include "levels/castle_grounds/areas/1/7/model.s"
.include "levels/castle_grounds/areas/1/8/model.s"
.include "levels/castle_grounds/areas/1/9/model.s"
.include "levels/castle_grounds/areas/1/10/model.s"
.include "levels/castle_grounds/areas/1/11/model.s"
.include "levels/castle_grounds/areas/1/11/anim.s"
.include "levels/castle_grounds/areas/1/12/model.s" # Letter
.ifdef VERSION_US
.include "levels/castle_grounds/areas/1/13/model.s" # Peach signature
.endif
.include "levels/castle_grounds/areas/1/collision.s"
.include "levels/castle_grounds/areas/1/macro.s"
.include "levels/castle_grounds/areas/1/7/collision.s"
.include "levels/castle_grounds/areas/1/8/collision.s"
.include "levels/castle_grounds/areas/1/movtext.s"
