# generated by n64split
.section .rodata
.include "macros.inc"
.include "PR/gbi.inc"

# Note: This bin does not use bin IDs, unlike the other segmented bins.

rawactor mario
rawactor bubble
rawactor walk_smoke
rawactor burn_smoke
rawactor stomp_smoke
rawactor water_wave
rawactor sparkle
rawactor water_splash
rawactor snowball2
rawactor sparkle_animation
