# generated by n64split
.section .rodata
.include "macros.inc"
.include "PR/gbi.inc"
.include "collision.inc"

initbinid
actor yellow_sphere_small
actor hoot
actor yoshi_egg
actor thwomp
actor bullet_bill
actor heave_ho
