# generated by n64split
.section .rodata
.include "macros.inc"
.include "PR/gbi.inc"
.include "collision.inc"

initbinid
actor mr_i_eyeball
actor mr_i_iris
actor swoop
actor snufit
actor dorrie
actor scuttlebug
