# generated by n64split
.section .rodata
.include "macros.inc"
.include "PR/gbi.inc"
.include "collision.inc"

initbinid
actor koopa_flag
actor poundable_pole
actor koopa
actor piranha_plant
actor whomp
actor chain_ball
actor chain_chomp
