# generated by n64split
.section .rodata
.include "macros.inc"
.include "PR/gbi.inc"
.include "collision.inc"
.include "macro_presets.inc"
.include "special_presets.inc"

.include "levels/wmotr/texture.s"
.include "levels/wmotr/areas/1/model.s"
.include "levels/wmotr/areas/1/collision.s"
.include "levels/wmotr/areas/1/macro.s"
