# Generated by LakiTool

glabel inside_castle_seg7_collision_floor_trap # 0x07078DE4 - 0x07078E14
colInit
colVertexInit 0x4
colVertex 358, 0, -306
colVertex 0, 0, -306
colVertex 0, 0, 307
colVertex 358, 0, 307
colTriInit SURF_ENV_DEFAULT, 2
colTri 0, 1, 2
colTri 0, 2, 3
colTriStop
colEnd
