# generated by n64split
.section .rodata
.include "macros.inc"
.include "PR/gbi.inc"
.include "collision.inc"
.include "macro_presets.inc"
.include "special_presets.inc"

.include "levels/cotmc/texture.s"
.include "levels/cotmc/areas/1/1/model.s"
.include "levels/cotmc/areas/1/2/model.s"
.include "levels/cotmc/areas/1/3/model.s"
.include "levels/cotmc/areas/1/collision.s"
.include "levels/cotmc/areas/1/macro.s"
.include "levels/cotmc/movtext.s"
