# generated by n64split
.section .rodata
.include "macros.inc"
.include "PR/gbi.inc"
.include "collision.inc"
.include "macro_presets.inc"
.include "special_presets.inc"

.include "levels/pss/texture.s"
.include "levels/pss/areas/1/1/model.s"
.include "levels/pss/areas/1/2/model.s"
.include "levels/pss/areas/1/3/model.s"
.include "levels/pss/areas/1/4/model.s"
.include "levels/pss/areas/1/5/model.s"
.include "levels/pss/areas/1/6/model.s"
.include "levels/pss/areas/1/7/model.s"
.include "levels/pss/areas/1/collision.s"
.include "levels/pss/areas/1/macro.s"
